### ISSUE TITLE
Bucket Policy

### ISSUE THREAD

**Issue by Kinfol** [MikeSouza/serverless-deployment-bucket#15]
Hi Mike,

Thanks for contributing.
Currently I can't see an example of how to pass a policy to the deployment bucket. 
I would assume would work smth like?

```
deploymentBucket:
name: ${self:custom.bucketName}
custom: 
   bucketName: ${someString}-suffix

//this file could be yml or json where S3 bucket would have defined it's properties and policys
//
Resources:
------
Properties:
    BucketName: ${self:custom.bucketName}
-------
Policy etc
```

**Comment by Kinfol** [comment]
The bellow example will get deployed, but the policy will not be applied to the bucket.
Furthermore, if I would like to put the policy in a different file, what would be a way to reference it under the policy tag?

```
provider:
  region: eu-west-2
  name: aws
  runtime: nodejs12.x
  deploymentBucket:
    name: bucket-name
    serverSideEncryption: AES256

custom:
  deploymentBucket:
    versioning: true
    policy: 
      {
        "Version": "2012-10-17",
        "Statement": [
        {
          "Effect": "Deny",
          "Principal": "*",
          "Action": "s3:*",
          "Resource": [
            "arn:aws:s3:::bucket-name",
            "arn:aws:s3:::bucket-name/*"
          ],
          "Condition": {
            "Bool": {
              "aws:SecureTransport": "false"
            }
          }
        }
        ]
      }
```

**Comment by Kinfol** [comment]
Problem has been addressed. The custom section needs to be above section provider. 

Next problem is how to reference ACL properties to the deployment bucket?

**Comment by MikeSouza** [comment]
```
provider:
  name: aws
  stage: ${opt:stage, 'development'}
  region: ${opt:region, "${env:AWS_REGION, 'us-east-1'}"}
  runtime: nodejs12.x
  deploymentBucket:
    name: some-bucket-${self:provider.region}-${self:provider.stage}
    serverSideEncryption: AES256

custom:
  deploymentBucket:
    versioning: true
    policy: "${file(bucket-policy.json)}"
```

`bucket-policy.json`
```
{
  "Version": "2012-10-17",
  "Id": "S3SecureTransportAndSSEPolicy",
  "Statement": [
    {
      "Sid": "ForceSSLOnlyAccess",
      "Effect": "Deny",
      "Principal": { "AWS": "*" },
      "Action": "s3:*",
      "Resource": "arn:aws:s3:::some-bucket-${self:provider.region}-${self:provider.stage}/*",
      "Condition": {
        "Bool": { "aws:SecureTransport": false }
      }
    },
    {
      "Sid": "DenyIncorrectEncryptionHeader",
      "Effect": "Deny",
      "Principal": "*",
      "Action": "s3:PutObject",
      "Resource": "arn:aws:s3:::some-bucket-${self:provider.region}-${self:provider.stage}/*",
      "Condition": {
        "StringNotEquals": {
          "s3:x-amz-server-side-encryption": "AES256"
        }
      }
    },
    {
      "Sid": "DenyUnEncryptedObjectUploads",
      "Effect": "Deny",
      "Principal": "*",
      "Action": "s3:PutObject",
      "Resource": "arn:aws:s3:::some-bucket-${self:provider.region}-${self:provider.stage}/*",
      "Condition": {
        "Null": {
          "s3:x-amz-server-side-encryption": "true"
        }
      }
    }
  ]
}
```
