### ISSUE TITLE
Controlling the directory structure of the deployment bucket.

### ISSUE THREAD

**Issue by mooperd** [MikeSouza/serverless-deployment-bucket#16]
Couple of points - 
- I would like to be able to control the path and filename of the assets that go into S3. currently it is something like:

s3://{deploymentBucket.name}/{service}/{service}/{stage}/{random-13-digit-number}-{iso-timestamp}/{service}.zip

for traceability I would prefer something like:

s3://{deploymentBucket.name}/{service}/{stage}/{git-commit-sha}.zip

```
service: serverless

plugins:
  - serverless-python-requirements

custom:
  app_acronym: wibble-foo
  stage: ${opt:branch}
  stack_name: ${self:custom.stage}-${self:custom.app_acronym}
  region: ${opt:region, self:provider.region}
  deletion_policy: Delete
  # Default to using app_acronym as bucket name
  s3_bucket: ${opt:s3_bucket, self:custom.app_acronym}
  # default to using ${stage} as key base path, keeps stages from namespace collisions
  s3_key_base: ${opt:s3_key_base, self:custom.stage}
  s3_bucket_arn: arn:aws:s3:::${self:custom.s3_bucket}
  s3_role_resource: ${self:custom.s3_bucket_arn}/${self:custom.s3_key_base}/*
  # Put this here rather than in code (presigned URL TTL)
  url_default_ttl: 60
  deploymentBucket:
    versioning: true


# The `provider` block defines where your service will be deployed
provider:
  name: aws
  stackName: ${self:custom.stack_name}
  stage: ${self:custom.stage}
  runtime: python3.8
  region: eu-west-1
  environment:
    S3_BUCKET: ${self:custom.s3_bucket}
    S3_KEY_BASE: ${self:custom.s3_key_base}
    URL_DEFAULT_TTL: ${self:custom.url_default_ttl}
  deploymentBucket:
    name: z7of-deployment-bucket


# The `functions` block defines what code to deploy
functions:
  helloWorld:
    name: ${self:custom.stack_name}-hello-world
    handler: handler.run
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      # Invoke Lambda function every minute
      - schedule: cron(* * * * ? *)
    iamRoleStatementsName: $${self:custom.stack_name}-role-lambda
    iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:*
        Resource: ${self:custom.s3_role_resource}
```
