### ISSUE TITLE
Location Constraint error

### ISSUE THREAD

**Issue by diego1686** [MikeSouza/serverless-deployment-bucket#23]
Hi, I'm getting this error

```
-------- Deployment Bucket Error --------
The us-west-2 location constraint is incompatible for the region specific endpoint this request was sent to.
```

This is my serverless.yml file

```
service: xxxxx

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2
  stage: ${opt:stage, 'dev'}
  versionFunctions: false
  timeout: 15

  deploymentBucket:
    name: test-deployments
    serverSideEncryption: AES256
```
