### ISSUE TITLE
Tagging bucket does not do anything

### ISSUE THREAD

**Issue by greghawk** [MikeSouza/serverless-deployment-bucket#41]
```
custom:
  deploymentBucket:
    tags:
      - Key: App
        Value: "name"
      - Key: Env
        Value: pr
```
