### ISSUE TITLE
Can I extend this to provide a toggle to enable S3 bucket logging?

### ISSUE THREAD

**Issue by gruckionvit** [MikeSouza/serverless-deployment-bucket#43]
Hi, nice plugin. I'm looking to add S3 bucket access logging.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-loggingconfig.html

Do you know if it's possible to modify the `Properties` of the deployment bucket? Specifically `LoggingConfiguration`?

I want to extend your plugin to allow me to specify a destination bucket name as a property.

```yml
custom:
  deploymentBucket:
    versioning: true
    accelerate: true
    loggingDestinationBucketName: !Ref MyOwnBucketResource
    blockPublicAccess: true
    tags:
      - Key: Environment
        Value: production
```
