### ISSUE TITLE
Cannot deploy from printed serverless.yaml

### ISSUE THREAD

**Issue by avnerenv0** [MikeSouza/serverless-deployment-bucket#44]
In Serverless v2 , I cannot deploy from an `sls print`ed yaml.
To recreate - this is an example yaml
```
service: sls-test
frameworkVersion: 2.30.3
enableLocalInstallationFallback: true
plugins:
  - serverless-deployment-bucket
provider:
  name: aws
  runtime: nodejs14.x
  stage: test
  region: 'us-east-1'
  versionFunctions: false
  deploymentBucket:
    name: 'bucket'
```

Running `sls deploy` will try to create the bucket.
Running 
```
> SLS_DEPRECATION_DISABLE='*' SLS_WARNING_DISABLE='*' sls print | grep -v "Serverless:" > printed.yaml
> sls deploy -c printed.yaml
```

will result in `Could not locate deployment bucket.` without attempting to create the deployment bucket.
