### ISSUE TITLE
cannot get blockPublicAccess to work

### ISSUE THREAD

**Issue by dhoulker** [MikeSouza/serverless-deployment-bucket#45]
Hello, 

Great plugin, thank you. 

We use it to create our deployment bucket, and also add server side encryption. 

I've tried to add tags and also set block public access, but it doesn't work for me. 

We are using `v1.4.3` , with this config:

```
deploymentBucket:
        name: 'com.ourproject.${self:provider.region}.${self:provider.stage}.deployments'
        blockPublicAccess: true
        tags:
            - Key: Key
              Value: value
        serverSideEncryption: AES256
```
When i run `sls deploy --stage mystage`, the bucket gets created, but with no tags and blockPublicAccess has no effect. 

Is there a step i'm missing?

Thanks,

Dave
