### ISSUE TITLE
Tags should support same format as provider.tags

### ISSUE THREAD

**Issue by estahn** [MikeSouza/serverless-deployment-bucket#78]
I'm using the following:
```yaml
  tags: &tags
    ManagedBy: Serverless Framework
    Service: ${self:service}
    Stage: ${sls:stage}
    Environment: ${sls:stage}
  stackTags:
    <<: *tags
```

I can not reuse the anchor with the bucket due to the current format.
