### ISSUE TITLE
serverSideEncryption not updated on already created bucket

### ISSUE THREAD

**Issue by irwingvw** [MikeSouza/serverless-deployment-bucket#82]
I have a bucket that has already been deloyed

```
provider:
  name: aws
  runtime: nodejs12.x
  region: ${opt:region}
  stage: ${opt:stage}
  env: ${opt:env}
  logRetentionInDays: 14
  apiGateway:
    disableDefaultEndpoint: true
  deploymentBucket:
    name: my-service-${self:provider.env}-${self:provider.region}-serverless-bucket
    serverSideEncryption: aws:kms
    kmsKeyID: ${${self:provider.env}-kms-s3-internal-key.ExportCMKAlias}
```

previously I had AES256 for serverSideEncryption and the serverless deploy runs just fine but after running I go check the bucket and it still has AES256.

If I change the bucket name so that it creates another one it works.
