### ISSUE TITLE
kmsKeyID is not recognized and fails deployment when configValidationMode is set to error

### ISSUE THREAD

**Issue by waggonerjake** [MikeSouza/serverless-deployment-bucket#84]
Having the property
```
frameworkVersion: '3'
configValidationMode: error
...
````
in your serverless.yaml while also having
```
provider:
  deploymentBucket:
    name: ${self:service}-deployment-bucket-${opt:stage}
    serverSideEncryption: aws:kms
    kmsKeyID: ${param:KEY_ALIAS_ARN}
```
will cause the deployment to fail due to `kmsKeyID` not being a recognized property. By switching to `configValidationMode: warn`, you can successfully deploy and have the bucket use the KMS key provided. If I want to keep the configValidationMode property as error, then I cannot use this to set up KMS encryption.

I am using serverless 3.22.0
